-- CREATE DATABASE bookarmarks;
-- psql -U dunder_mifflin bookmarks;


DROP TABLE IF EXISTS bookmarks;
CREATE TABLE bookmarks (id INTEGER primary key generated by default as identity , title text NOT NULL , rating INTEGER NOT NULL , url VARCHAR(255) NOT NULL , description text NOT NULL);

INSERT INTO bookmarks(title,rating,url,description )
VALUES
('Title 1', 5,'https://www.google.com/','Google bookarmark'),
('Title 2', 3,'https://www.google.com/','Google bookarmark'),
('Title 3', 4,'https://www.thinkful.com/','Thinkful bookarmark'),
('Title 4', 2,'https://www.fb.com/','FB bookarmark'),
('Title 5', 1,'https://www.microsoft.com/','Microsoft bookarmark'),
('Title 6', 2,'https://www.example.com/','example bookarmark'),
('Title 7', 3,'https://www.example.com/','example bookarmark'),
('Title 8', 4,'https://www.example.com/','example bookarmark'),
('Title 9', 5,'https://www.example.com/','example bookarmark'),
('Title 10', 5,'https://www.example.com/','example bookarmark');

